Updated to Angular 11
cloudnc/ngx-favicon pull request #13
Opened 2021-01-27 17:40 UTC by jfbenckhuijsen

2021-01-28 09:06 UTC, maxime1992 commented on angular.json
> +    "analytics": "dc2c4426-745f-406d-82f0-fdf9c84be24f"
I'd rather prefer not to have this

2021-01-28 09:56 UTC, jfbenckhuijsen commented on angular.json
> +    "analytics": "dc2c4426-745f-406d-82f0-fdf9c84be24f"
👍🏻

2021-01-28 12:57 UTC, maxime1992 requested changes
Tested locally, LGTM :+1: 

One last thing can you please run `yarn prettier:write` as there's a diff on that :+1: 

Will merge after :)

2021-01-28 17:08 UTC, jfbenckhuijsen commented
Fixed code style for ya ;)

2021-01-29 08:24 UTC, maxime1992 approved these changes

2021-01-29 08:25 UTC, merged

2021-01-29 08:26 UTC, maxime1992 commented
I messed up the squash :disappointed: 

I wanted to add a breaking change for the major bump but failed... By pressing enter to go to next line and it just sent the form :facepalm: 

sjhbsjhzegjhzbsjkbhgszjbfjsbvgfjhksbvag :upside_down_face: 

Thanks for the upgrade and the time spent on this @jfbenckhuijsen! :clap: